name: Turbopack Nightly Release

on:
  schedule:
    - cron: "15 8 * * *" # Run every day at 00:15 PST
  workflow_dispatch:

jobs:
  turbopack_nightly:
    name: Cut nightly Turbopack release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get latest commit that passes CI
        uses: talentpair/last-green-commit-action@bd55a9795105877107ab9fcb0368b3052662ea8f
        id: green_commit
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag nightly
        id: tag_version
        uses: ./.github/actions/turbopack-bump
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_sha: ${{ steps.green_commit.outputs.result }}
          prefix: "turbopack-"
